dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.0
  - smartcontractkit/chainlink@1.8.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0"
      - "@chainlink=smartcontractkit/chainlink@1.8.0"
networks:
  development:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
  goerli:
    verify: True
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
    fau_token: '0xBA62BCfcAaFc6622853cca2BE6Ac7d845BC0f2Dc'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    dai_usd_price_feed: '0x0d79df66BE487753B02D015Fb622DED7f0E9798d'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
